version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://test:test@postgres:5432/test
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
